# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-exploration/all/ruby-exploration.rbi
#
# ruby-exploration-0.1.0

module Ruby
end
module Ruby::Exploration
end
class Ruby::Exploration::Error < StandardError
end
